const DEFAULT={bg:'#eee8de',paper:'#f8f4ec',ink:'#282421',accent:'#8f6955',pageSize:12,gap:30,maxWidth:1400,previewLength:180};
let settings={...DEFAULT},data=[...works],page=1,filter='ALL',query='',sort='newest';
const REPO='cianyu1120-cmyk/jiangqie-commission',BRANCH='main';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function apply(){document.documentElement.style.setProperty('--gap',settings.gap+'px');document.documentElement.style.setProperty('--max-width',settings.maxWidth+'px')}
function token(){return sessionStorage.getItem('jqGithubToken')||''}
function save(){localStorage.setItem('jqWorks',JSON.stringify(data))}
function load(){try{const s=localStorage.getItem('jqWorks');if(s)data=JSON.parse(s)}catch(e){}apply()}
function encode64(text){return btoa(unescape(encodeURIComponent(text)))}
function worksFile(){return `const COMMON_TAGS=${JSON.stringify(COMMON_TAGS)};\nconst works=${JSON.stringify(data,null,2)};\n`}
async function githubRequest(path,options={}){const t=token();if(!t)throw Error('尚未連接 GitHub');const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){let x=await r.json().catch(()=>({}));throw Error(x.message||('GitHub API '+r.status))}return r.json()}
async function syncGithub(){const f=await githubRequest('works.js');const body={message:'Update commission works',content:encode64(worksFile()),sha:f.sha,branch:BRANCH};await githubRequest('works.js',{method:'PUT',body:JSON.stringify(body)});save()}
function setGithubStatus(text,bad=false){const el=$('#github-status');if(el){el.textContent=text;el.style.color=bad?'#9a4b3c':''}}
async function connectGithub(){const t=$('#github-token').value.trim();if(!t){setGithubStatus('請先貼上 token。',true);return}sessionStorage.setItem('jqGithubToken',t);try{await githubRequest('works.js');setGithubStatus('GitHub 已連接。現在儲存作品會直接更新網站資料。');$('#github-token').value='';}catch(e){sessionStorage.removeItem('jqGithubToken');setGithubStatus('連接失敗：'+e.message,true)}}
function tags(){const common=typeof COMMON_TAGS==='undefined'?[]:COMMON_TAGS;$('#tag-picker').innerHTML=common.map(t=>`<button type="button" data-tag="${esc(t)}">${esc(t)}</button>`).join('');$('#tag-picker').onclick=e=>{const b=e.target.closest('[data-tag]');if(!b)return;let a=$('#f-tags').value.split(',').map(x=>x.trim()).filter(Boolean),t=b.dataset.tag;a=a.includes(t)?a.filter(x=>x!==t):[...a,t];$('#f-tags').value=a.join(', ');syncTags()};$('#f-tags').oninput=syncTags}
function syncTags(){const a=$('#f-tags').value.split(',').map(x=>x.trim());document.querySelectorAll('#tag-picker button').forEach(b=>b.classList.toggle('selected',a.includes(b.dataset.tag)))}
function render(){let a=data.filter(w=>!w.private);if(filter!=='ALL')a=a.filter(w=>(w.tags||[]).includes(filter));if(query)a=a.filter(w=>(w.title+' '+w.description+' '+(w.tags||[]).join(' ')).toLowerCase().includes(query));a.sort((x,y)=>sort==='title'?x.title.localeCompare(y.title,'zh-Hant'):sort==='newest'?new Date(y.date)-new Date(x.date):new Date(x.date)-new Date(y.date));const n=Math.max(1,Math.ceil(a.length/settings.pageSize)),p=a.slice((page-1)*settings.pageSize,page*settings.pageSize);$('#total-count').textContent=String(a.length).padStart(3,'0');$('#result-count').textContent=`SHOWING ${a.length}`;$('#page-info').textContent=`PAGE ${page} / ${n}`;$('#works-grid').innerHTML=p.map(w=>{let q=(w.preview||'').slice(0,settings.previewLength);return `<a class="card" href="#work=${encodeURIComponent(w.id)}"><div class="paper"><div class="paper-head"><span>${esc(w.date)}</span><span>${w.r18?'R18':''}</span></div><div class="paper-title">${esc(w.title)}</div><div class="paper-rule"></div><p>${esc(q)}${q.length<(w.preview||'').length?'……':''}</p><div class="paper-tags">${(w.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="paper-foot"><span>${w.wordCount?Number(w.wordCount).toLocaleString()+' words':'SHORT FICTION'}</span><span>READ →</span></div></div><div class="card-info"><div><span>SHORT FICTION</span><h3>${esc(w.title)}</h3></div><time>${esc(w.date)}</time></div></a>`}).join('')||'<div class="empty">沒有符合條件的作品。</div>';let ph='';for(let i=1;i<=n;i++)ph+=`<button data-p="${i}" class="${i===page?'active':''}">${String(i).padStart(2,'0')}</button>`;$('#pagination').innerHTML=ph}
function readerBody(w){$('#reader-content').innerHTML=`<section class="reader-head"><span>SHORT FICTION / ${esc(w.date)}</span><h1>${esc(w.title)}</h1><div>${(w.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div></section><article class="reading">${(w.content||[]).map((x,i)=>`<p class="${i?'':'dropcap'}">${esc(x)}</p>`).join('')}</article>`}
function openReader(id){const w=data.find(x=>x.id===id);if(!w)return;if(w.r18){$('#reader-content').innerHTML=`<div class="warning"><span>RESTRICTED CONTENT</span><h2>閱讀提醒</h2><p>這篇作品包含成人向內容。若你未滿 18 歲，請不要繼續閱讀。</p><button id="continue">我已滿 18 歲，繼續閱讀</button></div>`;$('#continue').onclick=()=>readerBody(w)}else readerBody(w);$('#reader-overlay').classList.add('open')}
function admin(){const list=[...data].sort((a,b)=>new Date(b.date)-new Date(a.date));$('#admin-list').innerHTML=list.map(w=>`<div class="admin-row"><div><span>${w.private?'PRIVATE':'PUBLIC'}${w.r18?' · R18':''}</span><strong>${esc(w.title)}</strong><small>${esc(w.date)}</small></div><div class="admin-actions"><button data-a="view" data-id="${w.id}">閱覽</button><button data-a="edit" data-id="${w.id}">編輯</button><button data-a="toggle" data-id="${w.id}">${w.private?'公開':'隱藏'}</button><button data-a="del" data-id="${w.id}">刪除</button></div></div>`).join('')||'<p class="empty">還沒有作品。</p>'}
function form(id){const w=data.find(x=>x.id===id);$('#edit-id').value=w?.id||'';$('#f-title').value=w?.title||'';$('#f-date').value=w?.date||new Date().toISOString().slice(0,10);$('#f-words').value=w?.wordCount||'';$('#f-tags').value=(w?.tags||[]).join(', ');$('#f-description').value=w?.description||'';$('#f-preview').value=w?.preview||'';$('#f-content').value=(w?.content||[]).join('\n\n');$('#f-public').checked=!w?.private;$('#f-r18').checked=!!w?.r18;$('#form-mode').textContent=w?'EDIT WORK':'NEW WORK';syncTags();$('#admin-list-view').hidden=true;$('#work-form').hidden=false}
async function saveForm(e){e.preventDefault();if(!token()){alert('請先在 GitHub 同步區連接 GitHub。');return}const old=$('#edit-id').value,id=old||'work-'+Date.now().toString(36),w={id,title:$('#f-title').value.trim(),date:$('#f-date').value,status:'Completed',private:!$('#f-public').checked,r18:$('#f-r18').checked,tags:$('#f-tags').value.split(',').map(x=>x.trim()).filter(Boolean),wordCount:Number($('#f-words').value)||0,description:$('#f-description').value.trim(),preview:$('#f-preview').value.trim(),content:$('#f-content').value.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)};if(!w.title){alert('請填寫作品名稱');return}const i=data.findIndex(x=>x.id===id);if(i<0)data.unshift(w);else data[i]=w;try{setGithubStatus('正在同步 GitHub…');await syncGithub();setGithubStatus('已同步。GitHub Pages 更新可能需要幾十秒。');$('#work-form').hidden=true;$('#admin-list-view').hidden=false;admin();render()}catch(err){if(i<0)data.shift();else data[i]=works.find(x=>x.id===id)||data[i];setGithubStatus('同步失敗：'+err.message,true);alert('沒有寫入 GitHub：'+err.message)}}
function bind(){load();tags();render();if(token())setGithubStatus('已連接 GitHub（本次瀏覽器工作階段）。');$('#github-connect').onclick=connectGithub;$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.t;page=1;document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};const common=['ALL',...(typeof COMMON_TAGS!=='undefined'?COMMON_TAGS:[])];$('#filters').innerHTML=common.map((t,i)=>`<button data-t="${esc(t)}" class="${i?'':'active'}">${esc(t)}</button>`).join('');$('#search').oninput=e=>{query=e.target.value.toLowerCase();page=1;render()};$('#sort').onchange=e=>{sort=e.target.value;render()};$('#pagination').onclick=e=>{const b=e.target.closest('[data-p]');if(b){page=+b.dataset.p;render()}};$('#works-grid').onclick=e=>{const a=e.target.closest('a.card');if(a){e.preventDefault();openReader(decodeURIComponent(a.hash.slice(6)))}};$('#open-admin').onclick=()=>{$('#admin-panel').classList.add('open');admin()};$('#close-admin').onclick=()=>$('#admin-panel').classList.remove('open');$('#new-work').onclick=()=>form();$('#back-admin').onclick=()=>{$('#work-form').hidden=true;$('#admin-list-view').hidden=false;admin()};$('#cancel-form').onclick=()=>{$('#work-form').hidden=true;$('#admin-list-view').hidden=false};$('#work-form').onsubmit=saveForm;$('#admin-list').onclick=e=>{const b=e.target.closest('button[data-a]');if(!b)return;const id=b.dataset.id;if(b.dataset.a==='view')openReader(id);if(b.dataset.a==='edit')form(id);if(b.dataset.a==='toggle'){const w=data.find(x=>x.id===id);w.private=!w.private;save();if(token())syncGithub().then(()=>{admin();render()}).catch(err=>alert('同步失敗：'+err.message));else{admin();render()}}if(b.dataset.a==='del'&&confirm('確定刪除？')){const old=[...data];data=data.filter(x=>x.id!==id);if(token())syncGithub().then(()=>{admin();render()}).catch(err=>{data=old;alert('同步失敗：'+err.message)});else{save();admin();render()}}};$('#reader-close').onclick=()=>$('#reader-overlay').classList.remove('open');$('#open-customizer').onclick=()=>$('#customizer').classList.add('open');$('#close-customizer').onclick=()=>$('#customizer').classList.remove('open');document.querySelectorAll('#customizer [data-setting]').forEach(el=>el.oninput=()=>{let k=el.dataset.setting;settings[k]=el.type==='number'?+el.value:el.value;apply();render()})}
addEventListener('DOMContentLoaded',bind);
